---
title: "chapter1-3 R answers"
author: "Samuel"
date: "28/08/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Discussion questions

### Chapter 1

1. If we assume that a single locus contains two alleles, one for the red colour and one for the white, the dominant allele would be the one that is also expressed in the heterozygotes. Furthermore, reproduction between two heterozygous individuals is expected to produce a ratio 3:1 of dominant versus recessesive colouration. Dominance exists only when the heterozygote's phenotype measure lies closer to one homozygote than the other.

2. Most of the genetic diseases are recessesive because as soon as they expressed at the phenotypic level natural selection will purge them away.

3. If someone exercises every day, runs marathons, eats well, and is generally very healthy, the fitness is not passed on and the person's children still have to work just as hard to get that fit and healthy.

_I have changed my mind, writing the answers is taking me too long_

BEFORE DARWIN
Greek philosophers

### Chapter 2

### Chapter 3

1. The Hardy-Weinberg model hardly applies to any natural population. Why is it nevertheless useful?

2. In a small population, genetic drift will lead to a reduction in the frequency of heterozygotes relative the Hardy-Weinberg expectation - is this true or false? Discuss why.

3. Why is it that when an allele goes to fixation in a population, there are no heterozygotes but there is also no deviation from the Hardy-Weinberg expectation?
